#!/usr/bin/env bash
# prefetch-deps.sh — Regenerate deps.nix hashes for a new Wazuh version
#
# Usage:
#   ./prefetch-deps.sh [WAZUH_SOURCE_DIR]
#
# Where WAZUH_SOURCE_DIR is the path to an extracted Wazuh source tree
# (defaults to expecting the Makefile to be at ./src/Makefile).
#
# This script:
#   1. Reads DEPS_VERSION from src/Makefile
#   2. Downloads each source tarball listed in EXTERNAL_RES
#   3. Computes SHA256 SRI hashes using nix-prefetch-url
#   4. Outputs a complete deps.nix to stdout
#
# Requirements: nix-prefetch-url, nix hash command (NixOS or Nix installed)
#
# Example:
#   cd pkgs/by-name/wa/wazuh-agent
#   tar xf wazuh-4.14.3.tar.gz
#   ./prefetch-deps.sh ./wazuh-4.14.3 > deps.nix
#

set -euo pipefail

WAZUH_SRC="${1:-.}"
MAKEFILE="${WAZUH_SRC}/src/Makefile"

if [[ ! -f "$MAKEFILE" ]]; then
    echo "ERROR: Makefile not found at $MAKEFILE" >&2
    echo "Usage: $0 [WAZUH_SOURCE_DIR]" >&2
    exit 1
fi

# Read DEPS_VERSION from Makefile
DEPS_VERSION=$(grep '^DEPS_VERSION' "$MAKEFILE" | head -1 | sed 's/.*=\s*//' | tr -d ' ')
if [[ -z "$DEPS_VERSION" ]]; then
    echo "ERROR: Could not find DEPS_VERSION in $MAKEFILE" >&2
    exit 1
fi

# Read EXTERNAL_RES list
EXTERNAL_RES=$(grep '^EXTERNAL_RES :=' "$MAKEFILE" | head -1 | sed 's/EXTERNAL_RES :=\s*//')
HTTP_REQUEST_BRANCH=$(grep '^HTTP_REQUEST_BRANCH' "$MAKEFILE" | head -1 | sed 's/.*=\s*//' | tr -d ' ')

echo "# deps.nix — Auto-generated by prefetch-deps.sh" >&2
echo "# DEPS_VERSION = ${DEPS_VERSION}" >&2
echo "# Source: ${WAZUH_SRC}" >&2

BASE_URL="https://packages.wazuh.com/deps/${DEPS_VERSION}/libraries/sources"

get_sri() {
    local url="$1"
    local hash
    hash=$(nix-prefetch-url --unpack "$url" 2>/dev/null)
    if [[ $? -ne 0 ]]; then
        echo "FAILED"
        return
    fi
    nix hash convert --hash-algo sha256 "$hash" 2>/dev/null \
        || nix hash to-sri --type sha256 "$hash" 2>/dev/null \
        || echo "FAILED"
}

cat << 'HEADER'
# External dependency source tarballs for Wazuh agent.
# Generated by prefetch-deps.sh — do not edit manually.
# Run ./prefetch-deps.sh <wazuh-source-dir> > deps.nix to regenerate.
{ fetchurl }:
let
HEADER

echo "  depsVersion = \"${DEPS_VERSION}\";"
echo "  baseUrl = \"https://packages.wazuh.com/deps/\${depsVersion}/libraries/sources\";"
echo "  dep = name: hash: fetchurl {"
echo "    url = \"\${baseUrl}/\${name}.tar.gz\";"
echo "    inherit hash;"
echo "  };"
echo "in {"

for dep in $EXTERNAL_RES; do
    echo "  # Fetching $dep..." >&2
    SRI=$(get_sri "${BASE_URL}/${dep}.tar.gz")
    if [[ "$SRI" == "FAILED" ]]; then
        echo "  # TODO: FAILED to fetch ${dep}"
    else
        echo "  ${dep//-/_} = dep \"${dep}\" \"${SRI}\";"
    fi
done

# Add http-request
if [[ -n "$HTTP_REQUEST_BRANCH" ]]; then
    echo "  # Fetching http-request..." >&2
    HTTP_URL="https://github.com/wazuh/wazuh-http-request/tarball/${HTTP_REQUEST_BRANCH}"
    SRI=$(get_sri "$HTTP_URL")
    cat << EOF
  http-request = fetchurl {
    url = "${HTTP_URL}";
    hash = "${SRI}";
  };
EOF
fi

echo "}"
